In [1]:
import numpy as np

x = np.array([6, 20])

w = np.array([5, 0.2])

b = 10

z = np.dot(w, x) + b

print("Weighted sum:", z)

Weighted sum: 44.0


In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

output = sigmoid(z)

print("Neuron output:", output)

Neuron output: 1.0


In [3]:
def relu(z):
    return np.maximum(0, z)

for value in [-3, -1, 0, 2, 5]:
    print(value, "→", relu(value))

-3 → 0
-1 → 0
0 → 0
2 → 2
5 → 5


In [4]:
x = 2
y = 10

w = 3
b = 0

learning_rate = 0.1

for i in range(5):

    # Forward pass
    z = w * x + b
    prediction = max(0, z)  # ReLU

    # Loss
    loss = (y - prediction) ** 2

    # Backpropagation
    dL_dprediction = 2 * (prediction - y)

    # ReLU gradient
    dz_dprediction = 1 if z > 0 else 0

    # Gradient of weight
    dL_dw = dL_dprediction * dz_dprediction * x

    # Gradient descent
    w = w - learning_rate * dL_dw

    print(
        f"Step {i+1}: "
        f"prediction={prediction:.2f}, "
        f"loss={loss:.2f}, "
        f"weight={w:.2f}"
    )

Step 1: prediction=6.00, loss=16.00, weight=4.60
Step 2: prediction=9.20, loss=0.64, weight=4.92
Step 3: prediction=9.84, loss=0.03, weight=4.98
Step 4: prediction=9.97, loss=0.00, weight=5.00
Step 5: prediction=9.99, loss=0.00, weight=5.00


In [5]:
dL_db = dL_dprediction * dz_dprediction * 1

In [6]:
b = b - learning_rate * dL_db

In [7]:
x = 2
y = 10

w = 3
b = 0

learning_rate = 0.1

for i in range(5):

    # Forward pass
    z = w * x + b
    prediction = max(0, z)

    # Loss
    loss = (y - prediction) ** 2

    # Backpropagation
    dL_dprediction = 2 * (prediction - y)

    # ReLU gradient
    dz_dprediction = 1 if z > 0 else 0

    # Gradients
    dL_dw = dL_dprediction * dz_dprediction * x
    dL_db = dL_dprediction * dz_dprediction * 1

    # Update
    w = w - learning_rate * dL_dw
    b = b - learning_rate * dL_db

    print(
        f"Step {i+1}: "
        f"prediction={prediction:.2f}, "
        f"loss={loss:.2f}, "
        f"weight={w:.2f}, "
        f"bias={b:.2f}"
    )

Step 1: prediction=6.00, loss=16.00, weight=4.60, bias=0.80
Step 2: prediction=10.00, loss=0.00, weight=4.60, bias=0.80
Step 3: prediction=10.00, loss=0.00, weight=4.60, bias=0.80
Step 4: prediction=10.00, loss=0.00, weight=4.60, bias=0.80
Step 5: prediction=10.00, loss=0.00, weight=4.60, bias=0.80


In [2]:
%pip install torch torchvision torchaudio


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.3/127.3 MB 1.5 MB/s eta 0:00:0000:0100:03m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.9/679.9 kB 1.6 MB/s eta 0:00:00-:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.8 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 818.2/818.2 kB 1.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 819.1 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 721.9 kB/s eta 0:00:00:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [torchvision] [torchvision]

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch

print(torch.__version__)

2.14.0


In [4]:
x = [2]

In [5]:
import torch

x = torch.tensor([2.0])
y = torch.tensor([10.0])

print(x)
print(y)

tensor([2.])
tensor([10.])


In [6]:
import torch
import torch.nn as nn

neuron = nn.Linear(1, 1)

print(neuron)

Linear(in_features=1, out_features=1, bias=True)


In [7]:
x = torch.tensor([[2.0]])

output = neuron(x)

print(output)

tensor([[2.3140]], grad_fn=<AddmmBackward0>)


In [8]:
print("Weight:", neuron.weight)
print("Bias:", neuron.bias)

Weight: Parameter containing:
tensor([[0.7010]], requires_grad=True)
Bias: Parameter containing:
tensor([0.9121], requires_grad=True)


In [9]:
y = 10

In [10]:
y = torch.tensor([[10.0]])

loss_fn = nn.MSELoss()

loss = loss_fn(output, y)

print("Prediction:", output.item())
print("Loss:", loss.item())

Prediction: 2.3140439987182617
Loss: 59.07392120361328


In [11]:
loss.backward()


In [12]:
print("Weight gradient:", neuron.weight.grad)
print("Bias gradient:", neuron.bias.grad)

Weight gradient: tensor([[-30.7438]])
Bias gradient: tensor([-15.3719])
