In [1]:
import numpy as np

x = np.array([6, 20])

w = np.array([5, 0.2])

b = 10

z = np.dot(w, x) + b

print("Weighted sum:", z)

Weighted sum: 44.0


In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

output = sigmoid(z)

print("Neuron output:", output)

Neuron output: 1.0


In [3]:
def relu(z):
    return np.maximum(0, z)

for value in [-3, -1, 0, 2, 5]:
    print(value, "→", relu(value))

-3 → 0
-1 → 0
0 → 0
2 → 2
5 → 5


In [4]:
x = 2
y = 10

w = 3
b = 0

learning_rate = 0.1

for i in range(5):

    # Forward pass
    z = w * x + b
    prediction = max(0, z)  # ReLU

    # Loss
    loss = (y - prediction) ** 2

    # Backpropagation
    dL_dprediction = 2 * (prediction - y)

    # ReLU gradient
    dz_dprediction = 1 if z > 0 else 0

    # Gradient of weight
    dL_dw = dL_dprediction * dz_dprediction * x

    # Gradient descent
    w = w - learning_rate * dL_dw

    print(
        f"Step {i+1}: "
        f"prediction={prediction:.2f}, "
        f"loss={loss:.2f}, "
        f"weight={w:.2f}"
    )

Step 1: prediction=6.00, loss=16.00, weight=4.60
Step 2: prediction=9.20, loss=0.64, weight=4.92
Step 3: prediction=9.84, loss=0.03, weight=4.98
Step 4: prediction=9.97, loss=0.00, weight=5.00
Step 5: prediction=9.99, loss=0.00, weight=5.00


In [5]:
dL_db = dL_dprediction * dz_dprediction * 1

In [6]:
b = b - learning_rate * dL_db

In [7]:
x = 2
y = 10

w = 3
b = 0

learning_rate = 0.1

for i in range(5):

    # Forward pass
    z = w * x + b
    prediction = max(0, z)

    # Loss
    loss = (y - prediction) ** 2

    # Backpropagation
    dL_dprediction = 2 * (prediction - y)

    # ReLU gradient
    dz_dprediction = 1 if z > 0 else 0

    # Gradients
    dL_dw = dL_dprediction * dz_dprediction * x
    dL_db = dL_dprediction * dz_dprediction * 1

    # Update
    w = w - learning_rate * dL_dw
    b = b - learning_rate * dL_db

    print(
        f"Step {i+1}: "
        f"prediction={prediction:.2f}, "
        f"loss={loss:.2f}, "
        f"weight={w:.2f}, "
        f"bias={b:.2f}"
    )

Step 1: prediction=6.00, loss=16.00, weight=4.60, bias=0.80
Step 2: prediction=10.00, loss=0.00, weight=4.60, bias=0.80
Step 3: prediction=10.00, loss=0.00, weight=4.60, bias=0.80
Step 4: prediction=10.00, loss=0.00, weight=4.60, bias=0.80
Step 5: prediction=10.00, loss=0.00, weight=4.60, bias=0.80


In [8]:
%pip install torch torchvision torchaudio



[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [9]:
import torch

print(torch.__version__)

2.14.0


In [10]:
x = [2]

In [11]:
import torch

x = torch.tensor([2.0])
y = torch.tensor([10.0])

print(x)
print(y)

tensor([2.])
tensor([10.])


In [12]:
import torch
import torch.nn as nn

neuron = nn.Linear(1, 1)

print(neuron)

Linear(in_features=1, out_features=1, bias=True)


In [13]:
x = torch.tensor([[2.0]])

output = neuron(x)

print(output)

tensor([[-1.0754]], grad_fn=<AddmmBackward0>)


In [14]:
print("Weight:", neuron.weight)
print("Bias:", neuron.bias)

Weight: Parameter containing:
tensor([[-0.7063]], requires_grad=True)
Bias: Parameter containing:
tensor([0.3372], requires_grad=True)


In [15]:
y = 10

In [16]:
y = torch.tensor([[10.0]])

loss_fn = nn.MSELoss()

loss = loss_fn(output, y)

print("Prediction:", output.item())
print("Loss:", loss.item())

Prediction: -1.0753850936889648
Loss: 122.66415405273438


In [17]:
loss.backward()


In [18]:
print("Weight gradient:", neuron.weight.grad)
print("Bias gradient:", neuron.bias.grad)

Weight gradient: tensor([[-44.3015]])
Bias gradient: tensor([-22.1508])


In [19]:
optimizer = torch.optim.SGD(neuron.parameters(), lr=0.1)

optimizer.step()

print("Weight:", neuron.weight.item())
print("Bias:", neuron.bias.item())

Weight: 3.723843812942505
Bias: 2.5523126125335693


In [20]:
for epoch in range(10):
    optimizer.zero_grad()

    output = neuron(x)
    loss = loss_fn(output, y)

    loss.backward()
    optimizer.step()

    print(epoch, loss.item())

0 0.0
1 0.0
2 0.0
3 0.0
4 0.0
5 0.0
6 0.0
7 0.0
8 0.0
9 0.0


In [21]:
neuron = nn.Linear(1, 1)

optimizer = torch.optim.SGD(neuron.parameters(), lr=0.1)

for epoch in range(10):
    optimizer.zero_grad()

    output = neuron(x)
    loss = loss_fn(output, y)

    loss.backward()
    optimizer.step()

    print(
        f"Epoch {epoch+1}: "
        f"Prediction={output.item():.2f}, "
        f"Loss={loss.item():.2f}"
    )

Epoch 1: Prediction=-1.12, Loss=123.71
Epoch 2: Prediction=10.00, Loss=0.00
Epoch 3: Prediction=10.00, Loss=0.00
Epoch 4: Prediction=10.00, Loss=0.00
Epoch 5: Prediction=10.00, Loss=0.00
Epoch 6: Prediction=10.00, Loss=0.00
Epoch 7: Prediction=10.00, Loss=0.00
Epoch 8: Prediction=10.00, Loss=0.00
Epoch 9: Prediction=10.00, Loss=0.00
Epoch 10: Prediction=10.00, Loss=0.00


In [22]:
x_train = torch.tensor([
    [2.0],
    [4.0],
    [6.0],
    [8.0]
])

y_train = torch.tensor([
    [20.0],
    [40.0],
    [60.0],
    [80.0]
])

print(x_train)
print(y_train)

tensor([[2.],
        [4.],
        [6.],
        [8.]])
tensor([[20.],
        [40.],
        [60.],
        [80.]])


In [23]:
neuron = nn.Linear(1, 1)

predictions = neuron(x_train)

print(predictions)
print(predictions.shape)

tensor([[0.3323],
        [0.2504],
        [0.1684],
        [0.0865]], grad_fn=<AddmmBackward0>)
torch.Size([4, 1])


In [24]:
loss_fn = nn.MSELoss()

loss = loss_fn(predictions, y_train)

print("Predictions:")
print(predictions)

print("\nActual:")
print(y_train)

print("\nLoss:", loss.item())

Predictions:
tensor([[0.3323],
        [0.2504],
        [0.1684],
        [0.0865]], grad_fn=<AddmmBackward0>)

Actual:
tensor([[20.],
        [40.],
        [60.],
        [80.]])

Loss: 2983.207275390625


In [25]:
optimizer = torch.optim.SGD(neuron.parameters(), lr=0.01)

for epoch in range(100):
    optimizer.zero_grad()

    predictions = neuron(x_train)
    loss = loss_fn(predictions, y_train)

    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.2f}")

Epoch 0: Loss = 2983.21
Epoch 10: Loss = 0.65
Epoch 20: Loss = 0.61
Epoch 30: Loss = 0.57
Epoch 40: Loss = 0.53
Epoch 50: Loss = 0.50
Epoch 60: Loss = 0.47
Epoch 70: Loss = 0.44
Epoch 80: Loss = 0.41
Epoch 90: Loss = 0.39


In [26]:
print("Weight:", neuron.weight.item())
print("Bias:", neuron.bias.item())

print("\nPredictions:")
print(neuron(x_train))


Weight: 9.753019332885742
Bias: 1.4738768339157104

Predictions:
tensor([[20.9799],
        [40.4860],
        [59.9920],
        [79.4980]], grad_fn=<AddmmBackward0>)


In [27]:
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(1, 3),
    nn.ReLU(),
    nn.Linear(3, 1)
)

print(model)

Sequential(
  (0): Linear(in_features=1, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [28]:
predictions = model(x_train)

print(predictions)
print(predictions.shape)

tensor([[-0.3716],
        [-1.0396],
        [-1.7075],
        [-2.3755]], grad_fn=<AddmmBackward0>)
torch.Size([4, 1])


In [29]:
loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

for epoch in range(1000):
    optimizer.zero_grad()

    predictions = model(x_train)
    loss = loss_fn(predictions, y_train)

    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.2f}")

Epoch 0: Loss = 3173.20
Epoch 100: Loss = 554.01
Epoch 200: Loss = 500.95
Epoch 300: Loss = 500.02
Epoch 400: Loss = 500.00
Epoch 500: Loss = 500.00
Epoch 600: Loss = 500.00
Epoch 700: Loss = 500.00
Epoch 800: Loss = 500.00
Epoch 900: Loss = 500.00


In [30]:
print("Predictions:")
print(model(x_train))

print("\nActual:")
print(y_train)

Predictions:
tensor([[49.9999],
        [49.9999],
        [49.9999],
        [49.9999]], grad_fn=<AddmmBackward0>)

Actual:
tensor([[20.],
        [40.],
        [60.],
        [80.]])


In [31]:
model = nn.Sequential(
    nn.Linear(1, 3),
    nn.ReLU(),
    nn.Linear(3, 1)
)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.01
)

for epoch in range(1000):
    optimizer.zero_grad()

    predictions = model(x_train)
    loss = loss_fn(predictions, y_train)

    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.2f}")

Epoch 0: Loss = 3033.41
Epoch 100: Loss = 1274.70
Epoch 200: Loss = 24.53
Epoch 300: Loss = 7.48
Epoch 400: Loss = 6.57
Epoch 500: Loss = 5.65
Epoch 600: Loss = 4.75
Epoch 700: Loss = 3.91
Epoch 800: Loss = 3.14
Epoch 900: Loss = 2.46


In [32]:
print("Predictions:")
print(model(x_train))

print("\nActual:")
print(y_train)

print("\nFinal Loss:", loss.item())

Predictions:
tensor([[22.2115],
        [41.0726],
        [59.9338],
        [78.7949]], grad_fn=<AddmmBackward0>)

Actual:
tensor([[20.],
        [40.],
        [60.],
        [80.]])

Final Loss: 1.8797507286071777


In [33]:
x_train = torch.tensor([[2.0], [4.0], [6.0], [8.0]])
y_train = torch.tensor([[20.0], [40.0], [60.0], [80.0]])

In [34]:
from torch.utils.data import TensorDataset, DataLoader

dataset = TensorDataset(x_train, y_train)

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

for x_batch, y_batch in loader:
    print("X:", x_batch)
    print("Y:", y_batch)
    print()

X: tensor([[4.],
        [6.]])
Y: tensor([[40.],
        [60.]])

X: tensor([[2.],
        [8.]])
Y: tensor([[20.],
        [80.]])



In [35]:
model = nn.Linear(1, 1)

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):
    
    for x_batch, y_batch in loader:
        
        optimizer.zero_grad()
        
        predictions = model(x_batch)
        
        loss = loss_fn(predictions, y_batch)
        
        loss.backward()
        
        optimizer.step()
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.4f}")

Epoch 0: Loss = 838.4744
Epoch 10: Loss = 0.1534
Epoch 20: Loss = 0.1894
Epoch 30: Loss = 0.2840
Epoch 40: Loss = 0.2487
Epoch 50: Loss = 0.0433
Epoch 60: Loss = 0.1893
Epoch 70: Loss = 0.1103
Epoch 80: Loss = 0.1435
Epoch 90: Loss = 0.0452


In [36]:
model = nn.Linear(1, 1)

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):
    
    total_loss = 0
    
    for x_batch, y_batch in loader:
        
        optimizer.zero_grad()
        
        predictions = model(x_batch)
        
        loss = loss_fn(predictions, y_batch)
        
        loss.backward()
        
        optimizer.step()
        
        total_loss += loss.item()
    
    avg_loss = total_loss / len(loader)
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Avg Loss = {avg_loss:.4f}")

Epoch 0: Avg Loss = 1904.8703
Epoch 10: Avg Loss = 0.7361
Epoch 20: Avg Loss = 0.6923
Epoch 30: Avg Loss = 0.5695
Epoch 40: Avg Loss = 0.6252
Epoch 50: Avg Loss = 0.4287
Epoch 60: Avg Loss = 0.3645
Epoch 70: Avg Loss = 0.3263
Epoch 80: Avg Loss = 0.3043
Epoch 90: Avg Loss = 0.3144
